# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# APPS (vlc, protonvpn) in sccrathpad (see rules.conf)
exec-once = ~/.config/autostart/start_apps.sh

# Inicia o monitor de LEDs em background
exec-once = ~/.config/autostart/check_keys.sh

# cuvave audio boost
exec-once = easyeffects --gapplication-service
