# Opacity Variables - Managed by illogical-impulse
# Use these variables in your window rules:
# windowrulev2 = opacity $OPACITY_ACTIVE override $OPACITY_INACTIVE override, class:^(yourapp)$
$OPACITY_ACTIVE = 0.93
$OPACITY_INACTIVE = 0.84
# End Opacity Variables

# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Kitty rule for OPACITY_INACTIVE
windowrulev2 = opacity 1 override $OPACITY_INACTIVE override, class:^(kitty)$

# Rule for Dolphin transparency
windowrulev2 = opacity $OPACITY_ACTIVE override $OPACITY_INACTIVE override, class:^(org.kde.dolphin)$
windowrulev2 = opacity $OPACITY_ACTIVE override $OPACITY_INACTIVE override, class:^(dolphin)$

# Rule for Kate transparency
windowrulev2 = opacity $OPACITY_ACTIVE override $OPACITY_INACTIVE override, class:^(org.kde.kate)$
windowrulev2 = opacity $OPACITY_ACTIVE override $OPACITY_INACTIVE override, class:^(kate)$

windowrulev2 = opacity $OPACITY_ACTIVE override $OPACITY_INACTIVE override, title:^(.*Code.*)$

# ---------------------------------------------------------
# 768 (from dp-1) - (app width)/2
# BITWARDEN rules
windowrulev2 = workspace special, class:^(Bitwarden)$
windowrulev2 = float, class:^(Bitwarden)$
windowrulev2 = move 2 42, class:^(Bitwarden)
windowrulev2 = size 748 666, class:^(Bitwarden)
windowrulev2 = opacity $OPACITY_ACTIVE override $OPACITY_INACTIVE override, title:^(Bitwarden)

# VeraCrypt rules
windowrulev2 = workspace special, class:^(veracrypt)$
windowrulev2 = move 752 42, title:^(VeraCrypt)
windowrulev2 = opacity $OPACITY_ACTIVE override $OPACITY_INACTIVE override, title:^(VeraCrypt)

# PROTONVPN rules
windowrulev2 = workspace special, class:^(protonvpn-app)$
windowrulev2 = move 1668 42, title:^(Proton VPN)
windowrulev2 = size 100$ 666, title:^(Proton VPN)
windowrulev2 = opacity $OPACITY_ACTIVE override $OPACITY_INACTIVE override, title:^(Proton VPN)

# VLC rules
# windowrulev2 = monitor HDMI-A-1, class:^(vlc)$
windowrulev2 = workspace special, title:^(VLC media player)
windowrulev2 = float, title:^(VLC media player)
windowrulev2 = move 834 68.4%, class:^(vlc)$, title:^(VLC media player)
windowrulev2 = size 252 315, class:^(vlc)$, title:^(VLC media player)

# ---------------------------------------------------------

# VOLUMN MIXER rules
windowrulev2 = float, class:^(pavucontrol-qt)$
windowrulev2 = size 590 590, class:^(pavucontrol-qt)

# BTOP rules (need --class "btop-float" on load)
windowrulev2 = float, class:^(btop-float)
windowrulev2 = size 885 700, class:^(btop-float)
windowrulev2 = center, class:^(btop-float)


windowrulev2 = opacity $OPACITY_ACTIVE override $OPACITY_INACTIVE override, title:^(User 1 - Anki)


windowrulev2 = opacity $OPACITY_ACTIVE override $OPACITY_INACTIVE override, class:^(waterfox)$
windowrulev2 = opacity $OPACITY_ACTIVE override $OPACITY_INACTIVE override, class:^(librewolf)$
windowrulev2 = opacity $OPACITY_ACTIVE override $OPACITY_INACTIVE override, class:^(firefox)$

$OPACITY_NAV_HOM = 0.5

windowrulev2 = opacity $OPACITY_NAV_HOM override $OPACITY_NAV_HOM override, title:^(Waterfox)$
windowrulev2 = opacity $OPACITY_NAV_HOM override $OPACITY_NAV_HOM override, title:^(LibreWolf)$
windowrulev2 = opacity $OPACITY_NAV_HOM override $OPACITY_NAV_HOM override, title:^(Firefox)$

windowrulev2 = opacity 1.0 override 1.0 override, title:^(.*YouTube.*)$
windowrulev2 = opacity $OPACITY_ACTIVE override $OPACITY_ACTIVE override, title:^(.*WhatsApp.*|.*pdf.*|.*rtk.*)$

windowrulev2 = suppressevent activate, workspace:name:special:special
windowrulev2 = suppressevent activate, class:^(bitwarden)$
windowrulev2 = suppressevent maximize, class:^(Bitwarden)$

